services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: /Users/chanymac2/DB/postgres
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    restart: unless-stopped
